type = "directrequest"
schemaVersion = 1
name = "Weather_Api_Request_Test"
externalJobID = "64a46314-91a0-4129-8267-19b5bbd9224a"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0xD82f08722b8e24DA3ab608AB11E230dB0E0a5829"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    decode_log -> decode_cbor
    
    decode_cbor -> temperature
    decode_cbor -> humidity
    decode_cbor -> reporttime

    temperature  [type="http" method=GET url="$(decode_cbor.urlTemperature)" allowunrestrictednetworkaccess="true"]
    temperature_parse    [type="jsonparse" path="$(decode_cbor.pathTemperature)" data="$(temperature)"]
    temperature -> temperature_parse
    
    humidity          [type="http" method=GET url="$(decode_cbor.urlHumidity)" allowunrestrictednetworkaccess="true"]
    humidity_parse    [type="jsonparse" path="$(decode_cbor.pathHumidity)" data="$(humidity)"]
    humidity -> humidity_parse
    
    reporttime          [type="http" method=GET url="$(decode_cbor.urlReporttime)" allowunrestrictednetworkaccess="true"]
    reporttime_parse    [type="jsonparse" path="$(decode_cbor.pathReporttime)" data="$(reporttime)"]
    reporttime -> reporttime_parse

    temperature_parse -> encode_mwr
    humidity_parse -> encode_mwr
    reporttime_parse -> encode_mwr
    // MWR API does NOT auto populate the requestID.
    encode_mwr [type="ethabiencode"
                abi="(bytes32 requestId, string _temperature, string _humidity, string _reporttime)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"_temperature\\": $(temperature_parse), \\"_humidity\\": $(humidity_parse), \\"_reporttime\\": $(reporttime_parse)}"
                ]
    encode_tx  [type="ethabiencode"
                abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_mwr)}"
                ]
    submit_tx  [type="ethtx" to="0xD82f08722b8e24DA3ab608AB11E230dB0E0a5829" data="$(encode_tx)"]
    encode_mwr -> encode_tx -> submit_tx
"""
